// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Revenda.MigrationService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250422204511_MyNewMigration3")]
    partial class MyNewMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Revenda.Core.Entities.EnderecoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RevendaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RevendaId");

                    b.ToTable("EnderecosEntrega");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Bairro = "Distrito Industrial",
                            Cep = "13000100",
                            Cidade = "Campinas",
                            Complemento = "Galpão A",
                            Estado = "SP",
                            Logradouro = "Rua Principal",
                            Numero = "100",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Bairro = "Vila Industrial",
                            Cep = "13000200",
                            Cidade = "Campinas",
                            Estado = "SP",
                            Logradouro = "Avenida dos Expedicionários",
                            Numero = "2000",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Bairro = "Centro",
                            Cep = "20000050",
                            Cidade = "Rio de Janeiro",
                            Estado = "RJ",
                            Logradouro = "Rua das Flores",
                            Numero = "50",
                            RevendaId = new Guid("a2e1d7b3-5d0e-4f3a-8b0c-6a8d7c3e5f5b")
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProdutoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItensPedido");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PedidoId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProdutoId = "SKU-CERV-PILSEN-600",
                            Quantidade = 800
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            PedidoId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProdutoId = "SKU-REFRI-COLA-2L",
                            Quantidade = 400
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.ItemPedidoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProdutoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoClienteId");

                    b.ToTable("ItensPedidoCliente");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            PedidoClienteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ProdutoId = "SKU-CERV-PILSEN-600",
                            Quantidade = 120
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            PedidoClienteId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ProdutoId = "SKU-REFRI-COLA-2L",
                            Quantidade = 50
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.NomeContato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RevendaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RevendaId");

                    b.ToTable("NomesContato");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsPrincipal = true,
                            Nome = "Carlos Pereira",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsPrincipal = false,
                            Nome = "Ana Souza",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            IsPrincipal = true,
                            Nome = "Roberto Lima",
                            RevendaId = new Guid("a2e1d7b3-5d0e-4f3a-8b0c-6a8d7c3e5f5b")
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RevendaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TentativasEnvio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RevendaId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DataCriacao = new DateTime(2025, 4, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            DataEnvio = new DateTime(2025, 4, 21, 14, 15, 0, 0, DateTimeKind.Utc),
                            OrderId = "_ORD_KJHGFD",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a"),
                            Status = 2,
                            TentativasEnvio = 1
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.PedidoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificacaoCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RevendaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RevendaId");

                    b.ToTable("PedidosCliente");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            DataPedido = new DateTime(2025, 4, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            IdentificacaoCliente = "Bar Amigos da Esquina",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.RevendaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Revendas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a"),
                            Cnpj = "71039888000183",
                            Email = "contato@distribuidoraalegria.com.br",
                            NomeFantasia = "Distribuidora Alegria",
                            RazaoSocial = "Comércio de Bebidas Alegria Ltda."
                        },
                        new
                        {
                            Id = new Guid("a2e1d7b3-5d0e-4f3a-8b0c-6a8d7c3e5f5b"),
                            Cnpj = "51468333000178",
                            Email = "compras@pontocertobebidas.com",
                            NomeFantasia = "Ponto Certo Bebidas",
                            RazaoSocial = "Bebidas Geladas Sempre ME"
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RevendaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RevendaId");

                    b.ToTable("Telefones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Numero = "11999998888",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Numero = "1123456789",
                            RevendaId = new Guid("f5b5a6d8-7c3e-4a8d-b0f3-3a0e5d7b2e1a")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Numero = "21988887777",
                            RevendaId = new Guid("a2e1d7b3-5d0e-4f3a-8b0c-6a8d7c3e5f5b")
                        });
                });

            modelBuilder.Entity("Revenda.Core.Entities.EnderecoEntrega", b =>
                {
                    b.HasOne("Revenda.Core.Entities.RevendaEntity", "Revenda")
                        .WithMany("EnderecosEntrega")
                        .HasForeignKey("RevendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revenda");
                });

            modelBuilder.Entity("Revenda.Core.Entities.ItemPedido", b =>
                {
                    b.HasOne("Revenda.Core.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Revenda.Core.Entities.ItemPedidoCliente", b =>
                {
                    b.HasOne("Revenda.Core.Entities.PedidoCliente", "PedidoCliente")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoCliente");
                });

            modelBuilder.Entity("Revenda.Core.Entities.NomeContato", b =>
                {
                    b.HasOne("Revenda.Core.Entities.RevendaEntity", "Revenda")
                        .WithMany("NomesContato")
                        .HasForeignKey("RevendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revenda");
                });

            modelBuilder.Entity("Revenda.Core.Entities.Pedido", b =>
                {
                    b.HasOne("Revenda.Core.Entities.RevendaEntity", "Revenda")
                        .WithMany("Pedidos")
                        .HasForeignKey("RevendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revenda");
                });

            modelBuilder.Entity("Revenda.Core.Entities.PedidoCliente", b =>
                {
                    b.HasOne("Revenda.Core.Entities.RevendaEntity", "Revenda")
                        .WithMany("PedidosCliente")
                        .HasForeignKey("RevendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revenda");
                });

            modelBuilder.Entity("Revenda.Core.Entities.Telefone", b =>
                {
                    b.HasOne("Revenda.Core.Entities.RevendaEntity", "Revenda")
                        .WithMany("Telefones")
                        .HasForeignKey("RevendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revenda");
                });

            modelBuilder.Entity("Revenda.Core.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Revenda.Core.Entities.PedidoCliente", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Revenda.Core.Entities.RevendaEntity", b =>
                {
                    b.Navigation("EnderecosEntrega");

                    b.Navigation("NomesContato");

                    b.Navigation("Pedidos");

                    b.Navigation("PedidosCliente");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
